### ISSUE TITLE
Prevent sending empty messages on enter key press.

### ISSUE THREAD

**Issue by sims-kale** [ni3mumbaikar/anon-chat#7]
Users can send empty messages by pressing Enter without typing any text, resulting in blank messages cluttering the chat. Add a check to prevent sending empty messages to improve chat readability.

**Comment by arashveysi3** [comment]
Hey let me fix that if possible

**Comment by ni3mumbaikar** [comment]
Hi @arashveysi3  thank you for your interest. The bug is already fixed by @sims-kale. 
Connect with me on [linkedin](linkedin.com/in/ni3mumbaikar)
I will assign different issue, let me know if you need any help with your local setup. Go through both [frontend](https://github.com/ni3mumbaikar/anon-chat) and [backend](https://github.com/sims-kale/anonchats) repos

**Comment by arashveysi3** [comment]
> Hi @arashveysi3 thank you for your interest. The bug is already fixed by @sims-kale. Connect with me on [linkedin](linkedin.com/in/ni3mumbaikar) I will assign different issue, let me know if you need any help with your local setup. Go through both [frontend](https://github.com/ni3mumbaikar/anon-chat) and [backend](https://github.com/sims-kale/anonchats) repos

hey. sorry for my bad. didn't pay attention to self-assigned text.
and yes I'm open to anything that might help both my career and your projects :)
